### ISSUE TITLE
Sonargraph Integration: sonarqube-report.xml not found

### ISSUE THREAD

**Issue by Woumawoum** [SonarQubeCommunity/sonar-sonargraph#11]
Hello,
I have some difficulty to let sonarqube know about the location of " sonarqube-report.xml"
I configure as explained into the documentation and the " sonarqube-report.xml" is created, but it still not be found for Sonarqube.
sonarqube-report.xml exit on  ./build/sonargraph not on  ./target/sonargraph
i addresed on gradle.propreties, to access on ./build/sonargraph  as target path
but it seems not work.

could someone help me please?
here the executed-output 

woumgama@R1068WW10P MINGW64 /c/got_bahninfo/bahninformationservice-master (master)
$ gradle clean build sonargraphReport

> Task :bootJar
Property 'bootInf' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

> Task :bootStartScripts
Property 'mainClassName' is annotated with @Optional that is not allowed for @Internal properties. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

> Task :checkstyleMain
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\BahnInformationServiceApplication.java:11: Falsche lexikographische Reihenfolge des Imports von 'java.util.Arrays'. Sollte vor 'org.springframework.web.cors.UrlBasedCorsConfigurationSource' stehen. [CustomImportOrder]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\BahnInformationServiceApplication.java:13: Import-Anweisung für 'de.pentasys.bahnakademie.got.bahninformationservice.security.SecurityConstants.HEADER_STRING' ist an der falschen Stelle. Sollte in der Import-Gruppe 'STATIC' Gruppe stehen. Erwartet wird in dieser Zeile ein Import, der keiner Import-Gruppe entspricht. [CustomImportOrder]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\BahnInformationServiceApplication.java:26:5: Es fehlt ein Javadoc-Kommentar. [JavadocMethod]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\BahnInformationServiceApplication.java:28: Der Abstand zwischen der Deklaration der Variable 'source' und ihrer ersten Verwendung beträgt 5 (Obergrenze ist 4). Erwägen Sie, diese Variable final zu machen, wenn Sie den Wert schon vorher speichern müssen (vor Methodenaufrufen mit Nebenwirkungen auf den ursprünglichen Wert). [VariableDeclarationUsageDistance]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\domain\model\TrainListMock.java:12: Zeile ist 166 Zeichen lang (Obergrenze ist 126). [LineLength]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\security\WebSecurity.java:8: Import-Anweisung für 'de.pentasys.bahnakademie.got.bahninformationservice.security.SecurityConstants.*' ist an der falschen Stelle. Sollte in der Import-Gruppe 'STATIC' Gruppe stehen. Erwartet wird in dieser Zeile ein Import, der keiner Import-Gruppe entspricht. [CustomImportOrder]
[ant:checkstyle] [WARN] C:\got_bahninfo\bahninformationservice-master\src\main\java\de\pentasys\bahnakademie\got\bahninformationservice\security\WebSecurity.java:8: Stern-Importe der Form '.*' sollten vermieden werden - de.pentasys.bahnakademie.got.bahninformationservice.security.SecurityConstants.*. [AvoidStarImport]
Checkstyle rule violations were found. See the report at: file:///C:/got_bahninfo/bahninformationservice-master/build/reports/checkstyle/main.html
Checkstyle files with violations: 3
Checkstyle violations by severity: [warning:7]

> Task :sonargraphReport
Check if a new matching version can be downloaded.
Using SonargraphBuild installation: SonargraphBuild-10.2.1.627_2020-07-07
Adding report format 'xml', because prepareForSonarQube is configured.
Starting SonargraphBuild [Client: Gradle, Version: 10.2.1] ...
Memory Info: 117M[used] 330M[free] 448M[allocated] 455M[max]
Starting OSGi container...

 Success.

> Task :sonargraphReport
Started SonargraphBuild [10.2.1.627]
Report 'bahninformationservice_2020-08-06_07-47-34' was successfully created
Memory Info: 84M[used] 357M[free] 442M[allocated] 455M[max]
Stopped SonargraphBuild after 10685 ms.
SonargraphBuild: Completed successfully after 10695 ms.
SonargraphBuild auto-update info: Most recent version 'SonargraphBuild-10.2.1.627' is already installed.

BUILD SUCCESSFUL in 35s
16 actionable tasks: 16 executed

woumgama@R1068WW10P MINGW64 /c/got_bahninfo/bahninformationservice-master (master)
$ gradle sonarqube

> Task :sonarqube
SonarScanner will require Java 11 to run starting in SonarQube 8.x
Failed to import external issues report: C:\Users\woumgama\Documents\bahninformationservice\bahninformationservice\build\sonargraph
java.io.FileNotFoundException: C:\Users\woumgama\Documents\bahninformationservice\bahninformationservice\build\sonargraph (Zugriff verweigert)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.sonar.java.externalreport.CheckstyleSensor.importReport(CheckstyleSensor.java:67)
        at org.sonar.java.externalreport.ExternalIssueUtils.importIfExist(ExternalIssueUtils.java:45)
        at org.sonar.java.externalreport.CheckstyleSensor.lambda$execute$1(CheckstyleSensor.java:63)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.sonar.java.externalreport.CheckstyleSensor.execute(CheckstyleSensor.java:63)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:386)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:382)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:351)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy153.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:726)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:693)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:554)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:537)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:278)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:267)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at java.util.Optional.map(Optional.java:215)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

Sonargraph Integration: XML report file 'C:\got_bahninfo\bahninformationservice-master\target\sonargraph\sonargraph-sonarqube-report.xml' not found

BUILD SUCCESSFUL in 12s
4 actionable tasks: 1 executed, 3 up-to-date

here how i configure:
 in gradle.build:

sonarqube {
    properties {
        property 'sonar.projectName', 'got_BahnInformationService '
    }
}

sonargraph {
               // activationCode = "XXX"// for sonargraph architect
                activationCode = "XXX" // for sonargraphbuild
                autoUpdate = true
                qualityModelFile = "Sonargraph:Java.sgqm" // specify the quality model '
                prepareForSonarQube = true   /*Creates an XML report and stores it
                                                at ${basedir}/${target}/sonargraph/sonargraph-sonarqube-report.xml,
                                                where the SonarQube Sonargraph plugin expects it. */
                reportType = "full" // creates metric information of all levels
              // reportDirectory =  "build/sonargraph"// is the target directory for the created report
             failSet {
                failOnEmptyWorkspace = true
                include(issueType: "any", severity: "error", resolution: "none")
                include(issueType: "ArchitectureViolation")
               // include(issueType: "any", severity: "warning")
                exclude(issueType: "ThresholdViolation")
            }
}

in gradle.propreties:

org.gradle.java.home=C:/Program Files/Java/jdk1.8.0_251
systemProp.sonar.host.url=http://localhost:8082
systemprop.sonar.login=e71bd0fcde441c3c16265e2a33e3909409a2fe8e
org.gradle.warning.mode=all
systemProp.sonar.java.target= ./build
#sonar.java.binaries=build/
#systemprop.sonar.java.binaries=./build/classes

**Comment by ingmarkellner** [comment]
Hello,

thanks a lot for taking the time to post this problem description! 
Indeed, the Sonargraph SonarQube plugin searches for the report in the /target directory, which is the default for Maven, but not for Gradle.

You can override this location by specifying a System property via the command-line like this: 
gradle clean build sonargraphReport sonarqube 
**-Dsonar.sonargraph.integration:report.path=./build/sonargraph/sonargraph-sonarqube-report.xml**

I will update our documentation at http://eclipse.hello2morrow.com/doc/build/content/sonarqube_integration.html to make this more explicit.
And I will spend some time to replace the hardcoded default report location at /target with a dynamic lookup.

Best regards,
Ingmar

**Comment by ingmarkellner** [comment]
Just noticed that this is the wrong repo. 
Integration with SonarGraph 8 and later is handled by the project https://github.com/sonargraph/sonar-sonargraph-integration
I created the issue there: https://github.com/sonargraph/sonar-sonargraph-integration/issues/21

**Comment by ingmarkellner** [comment]
I implemented the correct lookup of the generated Sonargraph XML report for Gradle.
This version is not yet published to the SonarQube Plugin Marketplace. 
To install, you need to download the version 5.1.4 https://github.com/sonargraph/sonar-sonargraph-integration/releases/tag/Release-5.1.4 and manually copy it to <sonarqube-server>/extensions/plugins. Obviously, you need to delete the previous version of the Sonargraph plugin from that folder.
